moderate = true

database_user = "social_media_user"
database_password = "dummypassword"
host = "localhost"
port = 3306

enableSmsNotification = true
accountSId = "sid1"
authToken = "token1"

[ballerina.observe]
tracingEnabled=true
tracingProvider="jaeger"

[ballerinax.jaeger]
samplerParam=1.0